name: japx_example
description: Demonstrates how to use the japx plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  japx:
    path: ../

  cupertino_icons: ^1.0.5
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/
