name: japx
description: Lightweight JSON API parser
version: 1.0.0
repository: https://github.com/infinum/flutter-plugins-japx

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
